file1=open("file1.txt","r")
file2=open("file2.txt","r")
file3=open("file3.txt","w")
op=open("merged.txt","w")
op.write(file1.read())
op.write("/n")
op.write(file2.read())
file1.close()
file2.close()
op.close()
print("Files merged successfully")